name: Security check with Bandit

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-python@v7
        with:
          python-version: "3.12"

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit
        run: bandit -r custom_components/ -x tests
